# Generated by Django 6.0.4 on 2026-04-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('news', 'Новости'), ('politics', 'Политика'), ('sport', 'Спорт'), ('tech', 'Технологии'), ('culture', 'Культура')], default='news', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='posts/video_thumbnails/'),
        ),
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
