# Generated by Django 6.0.4 on 2026-04-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
        ('posts', '0002_alter_post_options_post_category_post_is_pinned_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_like_per_ip_per_post',
        ),
        migrations.AddField(
            model_name='like',
            name='visitor_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('post', 'visitor_id'), name='unique_like_per_visitor_per_post'),
        ),
    ]
